name: Upload Codecov
description: 上传覆盖率报告到 Codecov。

runs:
  using: composite
  steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        use_oidc: true
