name: Publish NPM
description: 发布包到 npm Registry。

inputs:
  stage:
    description: 是否执行 stage publish（预发布验证）。
    default: "false"

  tag:
    description: 发布时使用的 npm dist-tag。

runs:
  using: composite
  steps:
    - name: Publish to NPM
      run: vp pm $VP_PM_CMD --access public --no-git-checks $VP_PM_TAG -r
      shell: bash
      env:
        VP_PM_CMD: ${{ inputs.stage == 'true' && 'stage publish' || 'publish' }}
        VP_PM_TAG: ${{ inputs.tag != '' && format('--tag {0}', inputs.tag) || '' }}
