name: Release

on:
  workflow_call:
    inputs:
      github-release:
        description: 是否生成 GitHub Release 与 Changelog。
        required: false
        type: boolean
        default: true

      publish:
        description: 是否发布到 npm Registry。
        required: false
        type: boolean
        default: false

      stage:
        description: 是否执行 stage publish（预发布验证）。
        required: false
        type: boolean
        default: false

      build:
        description: 发布前执行的构建命令。
        required: false
        type: string
        default: ""

      tag:
        description: 发布时使用的 npm dist-tag。
        required: false
        type: string
        default: ""

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Setup Vite+
        uses: ../setup-vp
        with:
          fetch-all: true
          cache: false

      - name: Generate GitHub Changelog
        if: ${{ inputs.github-release }}
        continue-on-error: true
        run: vpx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: ${{ inputs.build != '' && (inputs.publish || inputs.stage) }}
        run: ${{ inputs.build }}

      - name: Publish to NPM
        if: ${{ inputs.publish || inputs.stage }}
        env:
          VP_PM_CMD: ${{ inputs.stage && 'stage publish' || 'publish' }}
          VP_PM_TAG: ${{ inputs.tag != '' && format('--tag {0}', inputs.tag) || '' }}
        run: vp pm $VP_PM_CMD --access public --no-git-checks $VP_PM_TAG -r
