name: Changelog

on:
  workflow_call:

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Setup Vite+
        uses: avotokyo/workflows/actions/core/setup@main
        with:
          fetch-all: true
          cache: false

      - name: Generate GitHub Changelog
        uses: avotokyo/workflows/actions/release/changelog@main
