name: Autofix

on:
  push:
    branches: [main]

  pull_request:

  workflow_call:
    inputs:
      command:
        description: 指定自动修复执行命令。
        required: false
        type: string
        default: vp check --fix

      os:
        description: 指定运行自动修复任务的操作系统。
        required: false
        type: string
        default: ubuntu-latest

jobs:
  autofix:
    name: Autofix
    runs-on: ${{ github.event_name == 'workflow_call' && inputs.os || 'ubuntu-latest' }}

    permissions:
      contents: read

    steps:
      - name: Setup Vite+
        uses: avotokyo/workflows/actions/core/setup@main
        with:
          fetch-all: false
          cache: true

      - name: Fix
        if: ${{ github.event_name != 'workflow_call' || inputs.command != '' }}
        uses: avotokyo/workflows/actions/core/run@main
        with:
          command: ${{ github.event_name == 'workflow_call' && inputs.command || 'vp check --fix' }}

      - name: Commit
        uses: avotokyo/workflows/actions/integrations/autofix-commit@main
