name: Publish

on:
  workflow_call:
    inputs:
      type:
        description: 发布类型（npm 或 github）。
        required: false
        type: string
        default: "npm"

      build:
        description: 发布前执行的构建命令。
        required: false
        type: string
        default: ""

      stage:
        description: 是否执行 stage publish（预发布验证）。
        required: false
        type: boolean
        default: false

      tag:
        description: 发布时使用的 npm dist-tag。
        required: false
        type: string
        default: ""

jobs:
  npm:
    if: ${{ inputs.type == 'npm' }}
    uses: ./.github/workflows/publish-npm.yml
    with:
      build: ${{ inputs.build }}
      stage: ${{ inputs.stage }}
      tag: ${{ inputs.tag }}

  github:
    if: ${{ inputs.type == 'github' }}
    uses: ./.github/workflows/publish-github.yml
    with:
      build: ${{ inputs.build }}
      stage: ${{ inputs.stage }}
      tag: ${{ inputs.tag }}
