name: Release

on:
  workflow_call:
    inputs:
      github-release:
        description: 是否生成 GitHub Release 与 Changelog。
        required: false
        type: boolean
        default: true

      publish:
        description: 是否发布到 Registry。
        required: false
        type: boolean
        default: false

      type:
        description: 发布类型（npm 或 github）。
        required: false
        type: string
        default: "npm"

      stage:
        description: 是否执行 stage publish（预发布验证）。
        required: false
        type: boolean
        default: false

      build:
        description: 发布前执行的构建命令。
        required: false
        type: string
        default: ""

      tag:
        description: 发布时使用的 npm dist-tag。
        required: false
        type: string
        default: ""

jobs:
  changelog:
    if: ${{ inputs.github-release }}
    uses: ./.github/workflows/release-changelog.yml

  publish:
    if: ${{ inputs.publish || inputs.stage }}
    uses: ./.github/workflows/release-publish.yml
    with:
      type: ${{ inputs.type }}
      build: ${{ inputs.build }}
      stage: ${{ inputs.stage }}
      tag: ${{ inputs.tag }}
